export const REQUEST_ROOM = 'REQUEST_ROOM';
export const RECEIVE_ROOM = 'RECEIVE_ROOM';
export const ROOM_OUT_OF_SYNC = 'ROOM_OUT_OF_SYNC';

export const REINFORCE_NODE_OPTIMISTIC = 'REINFORCE_NODE_OPTIMISTIC';
